### ISSUE TITLE
Choco package version are being rejected

### ISSUE THREAD

**Issue by flcdrg** [bridgecrewio/yor-choco#2]
Hi there, it looks like no one is monitoring the email address for your Chocolatey account - otherwise you would have seen the emails requesting changes to your Chocolatey package.

Please look into this asap, as it is frustrating as a package moderator to see lots of versions of your package coming through the moderation queue without any of the issues being addressed.

David

**Comment by JamesWoolfenden** [comment]
Issues resolved in next package
